### ISSUE TITLE
App doesn't run in container

### ISSUE THREAD

**Issue by webnostic** [ibm-messaging/kafka-java-vertx-starter#46]
# Bug

## Issue Summary

* Describe what you were doing when you observed the problem?
Containerizing the app using Dockerfile and then running it using "docker run" command.

* Did this used to work? If so what changed?
No.

* Was the error recoverable? Did you perform any maintenance or workaround?
UI doesn't come up.

## Environment

* OS: Mac OS
* Browser (version): Chrome

## How To Reproduce This Issue
Build the app in a docker container and attempt to bring the application up.

## Expected Behaviour
Containerized app runs normally on local machine.

**Comment by katheris** [comment]
@webnostic happy to close this now?

**Comment by webnostic** [comment]
Yes, thank you!
